server:
  port: 8888
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
      - application/xml
      - application/xhtml+xml
      - text/html
      - text/xml
      - text/plain
project:
  info:
    contact: meidongxu@baidu.com
    version: 0.0.1
    department: oped
    description: demo程序

custom:
  boot:
    iplist:
      enabled: false
    limit:
      enabled: false
    i18n:
      enabled: true
    iam:
      enabled: false
    trace:
      enabled: true
    args:
      enabled: true
    profiling:
      enabled: true
    spring:
      fox:
        enabled: true
        patterns:
          - /**
        api-info:
          title: demo

spring:
  aop:
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

